//AUTH
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

//LISTS
export const FETCH_ALL_LISTS_SUCCESS = 'FETCH_ALL_LISTS_SUCCESS';
export const FETCH_ALL_LISTS_FAIL = 'FETCH_ALL_LISTS_FAIL';

//LIST
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAIL = 'CREATE_LIST_FAIL';
export const UPDATE_SHARED_WITH_SUCCESS = 'UPDATE_SHARED_WITH_SUCCESS';
export const UPDATE_SHARED_WITH_FAIL = 'UPDATE_SHARED_WITH_FAIL';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAIL = 'UPDATE_LIST_FAIL';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAIL = 'DELETE_LIST_FAIL';
export const COMPLETE_LIST_SUCCESS = 'COMPLETE_LIST_SUCCESS';
export const COMPLETE_LIST_FAIL = 'COMPLETE_LIST_FAIL';
export const REACTIVATE_LIST_SUCCESS = 'REACTIVATE_LIST_SUCCESS';
export const REACTIVATE_LIST_FAIL = 'REACTIVATE_LIST_FAIL';
export const LIST_USER_REMOVED_SUCCESS = 'LIST_USER_REMOVED_SUCCESS';
export const LIST_USER_REMOVED_FAIL = 'LIST_USER_REMOVED_FAIL';

//LIST ITEMS

export const ADD_ITEM_TO_LIST_SUCCESS = 'ADD_ITEM_TO_LIST_SUCCESS';
export const ADD_ITEM_TO_LIST_FAIL = 'ADD_ITEM_TO_LIST_FAIL';
export const DELETE_ITEM_FROM_LIST_SUCCESS = 'DELETE_ITEM_FROM_LIST_SUCCESS';
export const DELETE_ITEM_FROM_LIST_FAIL = 'DELETE_ITEM_FROM_LIST_FAIL';
export const UPDATE_ITEM_ON_LIST_SUCCESS = 'UPDATE_ITEM_ON_LIST_SUCCESS';
export const LIST_ITEM_SUCCESS_SUCCESS = 'LIST_ITEM_SUCCESS_SUCCESS';
export const LIST_ITEM_SUCCESS_FAIL = 'LIST_ITEM_SUCCESS_FAIL';
export const LIST_ITEM_PROBLEM_SUCCESS = 'LIST_ITEM_PROBLEM_SUCCESS';
export const LIST_ITEM_PROBLEM_FAIL = 'LIST_ITEM_PROBLEM_FAIL';
export const LIST_ITEM_DELETE_SUCCESS = 'LIST_ITEM_DELETE_SUCCESS';
export const LIST_ITEM_DELETE_FAIL = 'LIST_ITEM_DELETE_FAIL';

//PROFILE

export const FETCH_ALL_PROFILES_SUCCESS = 'FETCH_ALL_PROFILES_SUCCESS';
export const FETCH_ALL_PROFILES_FAIL = 'FETCH_ALL_PROFILES_FAIL';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

//potentials

//ALERTS

export const SHOW_ALERT = 'SHOW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//MISC
