//AUTH
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

//LISTS
export const FETCH_ALL_LISTS = 'FETCH_ALL_LISTS';
export const FETCH_ALL_LISTS_FAIL = 'FETCH_ALL_LISTS_FAIL';
export const FETCH_ALL_USER_LISTS = 'FETCH_ALL_USER_LISTS';

//LIST
export const FETCH_LIST = 'FETCH_LIST';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST';
export const CREATE_LIST_FAIL = 'CREATE_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
export const UPDATE_LIST_FAIL = 'UPDATE_LIST_FAIL';
export const DELETE_LIST = 'DELETE_LIST';
export const DELETE_LIST_FAIL = 'DELETE_LIST';

//LIST ITEMS

export const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST';
export const ADD_ITEM_TO_LIST_FAIL = 'ADD_ITEM_TO_LIST_FAIL';
export const DELETE_ITEM_FROM_LIST = 'DELETE_ITEM_FROM_LIST';
export const UPDATE_ITEM_ON_LIST = 'UPDATE_ITEM_ON_LIST';
export const LIST_ITEM_SUCCESS = 'LIST_ITEM_SUCCESS';
export const LIST_ITEM_PROBLEM = 'LIST_ITEM_PROBLEM';

//PROFILE

export const FETCH_ALL_PROFILES_SUCCESS = 'FETCH_ALL_PROFILES_SUCCESS';
export const FETCH_ALL_PROFILES_FAIL = 'FETCH_ALL_PROFILES_FAIL';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

//potentials

//ALERTS

export const SHOW_ALERT = 'SHOW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// export const LIST_ITEM_SUCCESS = 'LIST_ITEM_SUCCESS';
// export const LIST_ITEM_FAIL = 'LIST_ITEM_FAIL';
// export const ADD_COMMENT_TO_LIST_ITEM = 'ADD_COMMENT_TO_LIST_ITEM';

//MISC
